swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/UserProfile'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserFullName'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/UserProfile'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/{bankId}/{month}:    
    get:
      security:
        - Bearer: []
      tags:
          - Transactions Module (in progress...)
      summary: Get all transactions per month
      description: API for fetching transations per month
      parameters:
        - in: path
          name: bankId
          type: string
          required: true
        - in: path
          name: month
          type: string
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '401':
          description: Unauthorized client error
        '404':
          description: Not found error
        '500':
          description: Internal Server Error
  /user/profile/{bankId}/{month}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
          - Transactions Module (in progress...)
      summary: Get a transaction by ID
      description: API for fetching transaction by ID
      parameters:
        - in: path
          name: bankId
          type: string
          required: true
        - in: path
          name: month
          type: string
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized client error
        '404':
          description: Not found error
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
          - Transactions Module (in progress...)
      summary: Add a transaction by ID
      description: API for Add transaction by ID
      parameters:
        - in: path
          name: bankId
          type: string
          required: true
        - in: path
          name: month
          type: string
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdated'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction updated with success
        '400': 
          description: Bad request error
        '401':
          description: Unauthorized client error
        '404':
          description: Not found error
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
          - Transactions Module (in progress...)
      summary: Put a transaction by ID
      description: API for fetching transaction by ID
      parameters:
        - in: path
          name: bankId
          type: string
          required: true
        - in: path
          name: month
          type: string
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdated'
      produces:
        - application/json
      responses:
        '201':
          description: Transaction updated with success
          schema:
            $ref: '#/definitions/Transaction'
        '400': 
          description: Bad request error
        '401':
          description: Unauthorized client error
        '404':
          description: Not found error
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module (in progress...)
      summary: Delete a transaction by ID
      description: API for delete transaction by ID
      parameters:
        - in: path
          name: bankId
          type: string
          required: true
        - in: path
          name: month
          type: string
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted with success
        '400': 
          description: Bad request error
        '401':
          description: Unauthorized client error
        '404':
          description: Not found error
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    properties:
      transactions: 
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction: 
    properties: 
      id:
        type: integer
      bankId:
        type: integer
      createdAt: 
        type: string
      updatedAt:
        type: string
      description: 
        type: string
      transactionType: 
        type: string 
      category: 
        type: string
      notes: 
        type: string
  TransactionUpdated: 
    properties: 
      category: 
        type: string
      notes: 
        type: string
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  UserFullName:
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      createdAt:
        type: string
      updatedAt:
        type: string 
      id:
        type: string